pinpoint/main/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('register/welcome/', views.welcome, name="welcome"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('', include('django.contrib.auth.urls')),
    path('my_profile/edit/', views.edit_profile, name='edit_profile'),
    path('my_profile/change_password/', views.change_password, name='change_passoword')
]

pinpoint/pinpoint/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('accounts/', include('main.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('view_content.urls')),
]

pinpoint/main/models.py
from django.db import models

# Create your models here.

pinpoint/view_content/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(help_text="Title of the post.", max_length=200)
    body = models.TextField(help_text="content of the post.", )
    date = models.DateTimeField(help_text="Date the post was created.", auto_now_add=True)
    author = models.ManyToManyField('auth.User', help_text="Relation to the post's authors")
    editor = models.ForeignKey('auth.User', help_text="The editor assigned to this post.",  on_delete=models.CASCADE, related_name='editor_of', null=True)
    needs_proofreading = models.BooleanField(help_text="", default=False)
    published = models.BooleanField(help_text="", default=False)
    comment = models.TextField(help_text="", null=True)
    categories = models.ManyToManyField('Category', help_text="")
    saved_users = models.ManyToManyField('auth.User', help_text="",  related_name='users')
    needs_approval = models.BooleanField(help_text="", default=False)

    def __str__(self):
        return self.title


class AuthorSubscription(models.Model):
    subscriber = models.ForeignKey('auth.User', help_text="User subscribing to author", on_delete=models.CASCADE, related_name='subscribed_to')
    author = models.ForeignKey('auth.User', help_text="", on_delete=models.CASCADE, related_name='subscriber')

    class Meta:
        unique_together = ('subscriber', 'author')

    def __str__(self):
        return self.subscriber.username + " is subscribed to " + self.author.username


class Category(models.Model):
    name = models.CharField(help_text="", max_length=100)
    subscribers = models.ManyToManyField('auth.User', help_text="")

    def __str__(self):
        return self.name


class RoleRequest(models.Model):
    group = models.ForeignKey('auth.Group', help_text="The role being requested", on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', help_text="The user requesting the role", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + ' is requesting the role: ' + self.group.name

pinpoint/main/forms.py
from django import forms
from django.forms.models import modelform_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=32, help_text='First name')
    last_name = forms.CharField(max_length=32, help_text='Last name')
    email = forms.EmailField(max_length=64, help_text='Enter a valid email address')

    class Meta(UserCreationForm.Meta):
        model = User
        # I've tried both of these 'fields' declaration, result is the same
        # fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email',)


class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(max_length=32, help_text='First name')
    last_name = forms.CharField(max_length=32, help_text='Last name')
    email = forms.EmailField(max_length=64, help_text='Enter a valid email address')

    class Meta():
        model = User
        # I've tried both of these 'fields' declaration, result is the same
        # fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
        fields =  ('first_name', 'last_name', 'email')



      

pinpoint/main/views.py
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignUpForm, UserEditForm


def register(request):
    """Shows a register form."""
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('welcome/')
    else:
        form = SignUpForm()
    return render(request, 'registration/register.html', {'form': form})


def logout_view(request):
    """Logs the user out. Redirects to /accounts/login"""
    logout(request)
    return redirect('/accounts/login')


def welcome(request):
    """Redirects to /accounts/profile"""
    return redirect("/accounts/profile")


def profile(request):
    """Redirects to / (index)"""
    return redirect("/")


def edit_profile(request):
    """Lets user change their personal information."""
    initial = request.user.__dict__
    user = request.user
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, user)
            return redirect("/my_profile/")
    else:
        form = UserEditForm(instance=user)
        return render(request, "view_content/edit_profile.html", {'form': form, 'user': user})
    

def change_password(request):
    """Lets the user change their password"""
    initial = request.user.__dict__
    if request.method == 'POST':
        form = SetPasswordForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("/my_profile/")
    else:
        form = SetPasswordForm(request.user)
        return render(request, "view_content/edit_profile.html", {'form': form})

pinpoint/main/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Spectral" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <title>{% block title %}title{% endblock %}</title>
    <style>
    <style>
    body{
      font-family: 'Cormorant', serif;
    }
    textarea{
      border-radius: 10px;
      height: 25%;
      width: 100%;
      padding:20px;
    }

    input[type="text"], input[type="password"] {
      border-radius: 10px;
      height: 30px;
    }
    select{
      border-radius: 10px;
      height:30px;
    }
    
    .form-control-borderless {
      border: none;
    }

    .pointer{
      cursor: pointer;
    }

    #id_categories, #id_author{
      list-style-type: none;
    }

    
  </style>
  </head>
  <body>
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <a  class="navbar-brand" href="{% url 'home' %}">Pinpoint</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'content' %}">Create Content</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'subscriptions' %}">My subscriptions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'saved_posts' %}">Saved Posts</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Sign up</a>
        </li>
        {% endif %}
        </ul>
        <ul class="navbar-nav justify-content-end">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My sites
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'executive_page' %}">Executive page</a>
            <a class="dropdown-item" href="{% url 'my_page' %}">My page</a>
            <a class="dropdown-item" href="{% url 'my_profile' %}">My profile</a>
          </div>
        </li>
        <li class="btn btn-primary btn-sm">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="btn btn-primary btn-sm">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        </ul>
      </ul>
    </div>
  </nav>
  <br>
  <div class="shadow-lg p-3 mb-5 bg-white rounded" style="padding: 20px; width: 70%; margin: auto; margin-top: 20px; font-family: 'Spectral', serif;">
    {% block content %}

    {% endblock %}
  </div>
  <center><div> {% if request.user.is_authenticated %}Logged in as {{ request.user }} {% endif %}</div></center>
  <br><br>
  <center><small>Copyright &copy; Pinpoint - All rights Reserved </small></center>
  <center>Version: 4.0</center>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>